name: dart_signals
version: 0.0.1
author: '"Tomas Polovincak <polovincak.tomas@gmail.com>"'
description: Dartlang test implementation of QT(pyQT) signal/slot mechanism.
homepage: https://github.com/polovi/dart_signals.git
dependencies:
  unittest: any
